# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Backup
version:      0.06
version_from: lib/File/Backup.pm
installdirs:  site
requires:
    Carp:                          0
    Cwd:                           0
    File::Which:                   0
    LockFile::Simple:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
